resources:

- name: repo
  type: git
  source:
    uri: https://github.com/ndarilek/concourse-rancher-compose-resource
    branch: master

- name: image
  type: docker-image
  source:
    username: {{registry_username}}
    email: {{registry_email}}
    password: {{registry_password}}
    repository: nolan/concourse-rancher-compose-resource

jobs:

- name: test
  public: true
  plan:

  - get: repo
    trigger: true

  - task: run tests
    file: repo/concourse/test.yml

- name: build
  public: true
  plan:

  - get: repo
    trigger: true
    passed: [test]

  - put: image
    params:
      build: repo
